name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2dev/ps2dev:latest

    steps:
      - name: Install dependencies
        run: |
          apk add build-base cmake

      - uses: actions/checkout@v4
      - name: Compile project
        run: |
          mkdir build && cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=$PS2DEV/ps2sdk/ps2dev.cmake ..
          make -j $(getconf _NPROCESSORS_ONLN) clean 
          make -j $(getconf _NPROCESSORS_ONLN) all

      - name: Get short SHA
        id: slug
        run: |
          echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
    
      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: filesystem-test-${{ steps.slug.outputs.sha8 }}
          path: filesystem-test.elf